[package]
name = "silc-test"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dev-dependencies]
insta.workspace = true
proptest.workspace = true
assert_cmd.workspace = true
predicates.workspace = true
silc-frontend.workspace = true
silc-causal-ir.workspace = true
silc-backend.workspace = true

[[bench]]
name = "lexer_bench"
harness = false

[dependencies]
criterion.workspace = true
