[package]
name = "silc-runtime"
version = "0.1.0"
description = "Runtim-e/support library for SIL language components"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
libc.workspace = true

[build-dependencies]
cc.workspace = true
